 version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Hurray Mekhsss"
          command: "echo Mekha!"

  say-bye:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "Byeeee"
          command: "echo Bye Bye!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-bye:
          requires:
            - say-hello
